// src/app/layout.js
import { Geist } from 'next/font/google';
import './globals.css';
import Footer from '@/components/Footer';
import NavBar from '@/components/NavBar';
import { AppProvider } from './context/AppContext';
import FloatingCartButton from '@/components/FloatingCartButton';

const geistSans = Geist({
  subsets: ['latin'],
  variable: '--font-geist-sans',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased flex flex-col min-h-screen`}>
        <AppProvider>
          <NavBar />
          {/* FloatingCartButton es Client Component, no importa */}
          <FloatingCartButton />
          <main className="flex-grow">{children}</main>
          <Footer />
        </AppProvider>
      </body>
    </html>
  );
}
